# Generated by Django 5.0.2 on 2024-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0002_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='interiorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='interiordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='propertydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('sqft', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Area',
            new_name='CategoryName',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='floor',
            new_name='description',
        ),
    ]
