# Generated by Django 5.0.2 on 2024-03-06 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0003_interiorcategory_interiordb_propertydb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interior_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sqft', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='interiordb',
        ),
        migrations.DeleteModel(
            name='propertydb',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='interiorcategory',
            name='RoomName',
        ),
        migrations.AddField(
            model_name='interiorcategory',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='interiorcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interiorcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interior_category_images/'),
        ),
        migrations.AddField(
            model_name='interior',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminmodule.interiorcategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminmodule.category'),
        ),
    ]
