# Generated by Django 5.0.2 on 2024-03-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0004_interior_property_delete_interiordb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interior',
            name='name',
        ),
    ]
