# Generated by Django 5.0.2 on 2024-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0005_remove_interior_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='status_images/')),
            ],
        ),
    ]
