# Generated by Django 5.0.2 on 2024-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interior_images/'),
        ),
    ]
