# Generated by Django 5.0.2 on 2024-03-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interior_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminmodule.interiorcategory')),
            ],
        ),
    ]
