# Generated by Django 5.0.2 on 2024-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0009_renovation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interior_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='renovation',
            name='category',
            field=models.TextField(),
        ),
    ]
