# Generated by Django 5.0.2 on 2024-03-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0010_balance_alter_renovation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renovation',
            old_name='category',
            new_name='name',
        ),
    ]
