# Generated by Django 5.0.2 on 2024-03-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0011_rename_category_renovation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
