# Generated by Django 5.0.2 on 2024-03-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0012_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
