# Generated by Django 5.0.2 on 2024-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0015_alter_property_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interior_images/')),
            ],
        ),
    ]
