# Generated by Django 5.0.2 on 2024-03-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0016_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='admin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
