# Generated by Django 5.0.2 on 2024-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_images/'),
        ),
    ]
