# Generated by Django 5.0.2 on 2024-03-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0018_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
