# Generated by Django 5.0.2 on 2024-03-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0019_rename_receiver_message_receivers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receivers',
            new_name='receiver',
        ),
    ]
