# Generated by Django 5.0.2 on 2024-04-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0020_rename_receivers_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='CoustomerName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
