# Generated by Django 5.0.2 on 2024-04-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0021_status_coustomername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='CoustomerName',
            new_name='CustomerName',
        ),
    ]
