# Generated by Django 5.0.2 on 2024-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0022_rename_coustomername_status_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovation',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
