# Generated by Django 5.0.2 on 2024-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0024_alter_balance_image_alter_renovation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interior_images/'),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interior_images/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interior_images/'),
        ),
    ]
