# Generated by Django 5.0.2 on 2024-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0028_remove_message_user_ids_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin_message',
            field=models.BooleanField(default=False),
        ),
    ]
