# Generated by Django 5.0.2 on 2024-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0028_alter_property_plan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='CustomerName',
        ),
        migrations.AlterField(
            model_name='property',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_images/'),
        ),
    ]
