# Generated by Django 5.0.2 on 2024-04-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0029_remove_status_customername_alter_property_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovation',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='balance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Balance_images/'),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='renovation_images/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='status_images/'),
        ),
    ]
