# Generated by Django 5.0.2 on 2024-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0030_rename_message_message_message_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_on',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_admin_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='adminname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
