# Generated by Django 5.0.2 on 2024-03-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0031_rename_created_on_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='adminname',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='sender',
        ),
    ]
