# Generated by Django 5.0.2 on 2024-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0032_remove_renovation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('AdvanceAmound', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Labourcost', models.CharField(max_length=100, null=True)),
                ('Materialcost', models.CharField(max_length=100, null=True)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
    ]
