# Generated by Django 5.0.2 on 2024-03-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0033_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
