# Generated by Django 5.0.2 on 2024-04-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0034_rename_username_fullpay_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepay',
            old_name='AdvanceAmound',
            new_name='AdvanceAmount',
        ),
    ]
