# Generated by Django 5.0.2 on 2024-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminmodule', '0036_alter_advancepay_advanceamount_alter_fullpay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='CustomerName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
