# Generated by Django 5.0.2 on 2024-03-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usermodule', '0002_contactbd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationDb',
        ),
    ]
