# Generated by Django 5.0.2 on 2024-03-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usermodule', '0003_appointmentrequest_delete_contactbd_and_more'),
        
    ]

    operations = [
    ]
