# Generated by Django 5.0.2 on 2024-03-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usermodule', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
