# Generated by Django 5.0.2 on 2024-03-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usermodule', '0007_remove_order_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order_Address',
        ),
    ]
