# Generated by Django 5.0.2 on 2024-05-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usermodule', '0008_rename_order_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order_address',
            name='state',
        ),
    ]
